name: gtrepo
on:
  push:
    tags:
      - 'vu[0-9]+.[0-9]+.[0-9]+'
      
      
      
  workflow_dispatch:



jobs:
    job1:
        name: uniTest
        runs-on: ubuntu-latest
        permissions:
            checks: write
            contents: write
        # Map a step output to a job output
        outputs:
          output1: ${{ steps.step4.outputs.test }}
          
        steps:
          - name: Git checkout
            id: step1
            uses: actions/checkout@v3

           # Installation Styles and Saxon
      
          - name: install analyse xsl-styles
            id: step2
            run: | 
                git clone https://github.com/tboenig/gt-repo-scripts.git
                mv gt-repo-scripts/scripts scripts/
                rm -r gt-repo-scripts
          
          - name: Download and install saxon
            id: step3
            run: |
              wget https://github.com/Saxonica/Saxon-HE/releases/download/SaxonHE12-3/SaxonHE12-3J.zip 
              unzip SaxonHE12-3J.zip      
          
          - name: make gh-pages_out
            run: mkdir unitTest


          - name: Get SDK Version from config
            id: useyq
            uses: mikefarah/yq@master
            with:
             cmd: yq -o=json METADATA.yml > METADATA.json  

          - name: PathTest
            run: |
                java -jar saxon-he-12.3.jar -xsl:scripts/gt-overview_unitTest.xsl \
                output=unitTest1 \
                -s:scripts/gt-overview_unitTest.xsl -o:unitTest/pathtest.md
            shell: bash

          - name: Empty
            id: step4
            run: |
                [ -s unitTest/pathtest.md ] || echo "test=empty" >> "$GITHUB_OUTPUT"
            
    job2:
       name: makebagit
       runs-on: ubuntu-latest
       needs: job1
       if: ${{needs.job1.outputs.output1}} == 'empty'
       steps:
        - name: make ocrdzip_out
          run: |
            mkdir ocrdzip_out
            ls
      